// ─────────────────────────────────────────────────────────────────────────────
//  RNF Codegen  –  LLVM IR text emitter + build pipeline
//  Produces static, stripped, musl-linked binaries
// ─────────────────────────────────────────────────────────────────────────────

use std::collections::HashMap;
use std::path::Path;
use colored::Colorize;
use crate::ast::*;

// ── LLVM IR Generator ─────────────────────────────────────────────────────────

pub struct LlvmCodegen {
    module_name: String,
    str_lits:    Vec<String>,         // string constant pool
    str_map:     HashMap<String, usize>,
    tmp:         usize,               // temp register counter
    label:       usize,               // label counter
    functions:   HashMap<String, FunctionDecl>,
    structs:     HashMap<String, StructDecl>,
    locals:      HashMap<String, (String, LLVMType)>, // name → (reg, type)
}

#[derive(Debug, Clone, PartialEq)]
enum LLVMType {
    I1,
    I64,
    Double,
    Ptr,
    Void,
}

impl LLVMType {
    fn ir(&self) -> &'static str {
        match self {
            LLVMType::I1     => "i1",
            LLVMType::I64    => "i64",
            LLVMType::Double => "double",
            LLVMType::Ptr    => "i8*",
            LLVMType::Void   => "void",
        }
    }
}

fn ast_type_to_llvm(t: &Type) -> LLVMType {
    match t {
        Type::Int     => LLVMType::I64,
        Type::Float   => LLVMType::Double,
        Type::Str     => LLVMType::Ptr,
        Type::Bool    => LLVMType::I1,
        Type::Void    => LLVMType::Void,
        Type::Ptr(_)  => LLVMType::Ptr,
        Type::Chan(_) => LLVMType::Ptr,
        Type::Array(..)=> LLVMType::Ptr,
        Type::Custom(_)=> LLVMType::Ptr,
    }
}

impl LlvmCodegen {
    pub fn new(module_name: &str) -> Self {
        LlvmCodegen {
            module_name: module_name.to_string(),
            str_lits:    Vec::new(),
            str_map:     HashMap::new(),
            tmp:         0,
            label:       0,
            functions:   HashMap::new(),
            structs:     HashMap::new(),
            locals:      HashMap::new(),
        }
    }


    fn new_tmp(&mut self) -> usize { let t = self.tmp; self.tmp += 1; t }

    fn new_label(&mut self) -> usize { let l = self.label; self.label += 1; l }

    fn intern_str(&mut self, s: &str) -> usize {
        if let Some(&idx) = self.str_map.get(s) { return idx; }
        let idx = self.str_lits.len();
        self.str_lits.push(s.to_string());
        self.str_map.insert(s.to_string(), idx);
        idx
    }

    // ── Public entry ─────────────────────────────────────────────────────────

    pub fn generate(&mut self, program: &Program) -> Result<String, String> {
        // Collect declarations
        for item in &program.items {
            match item {
                TopLevel::Function(f) => { self.functions.insert(f.name.clone(), f.clone()); }
                TopLevel::Struct(s)   => { self.structs.insert(s.name.clone(), s.clone()); }
                _ => {}
            }
        }

        // Build string pool first (scan everything)
        // We'll intern strings during codegen and generate the pool after

        // Module header
        let header = format!(
r#"; RNF Compiled Module: {}
; Generated by rnf compiler — https://github.com/risqinf/rnf

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-musl"

; ── libc declarations ──────────────────────────────────────────────────────────
declare i32 @printf(i8* noundef, ...)
declare i32 @fprintf(i8* noundef, i8* noundef, ...)
declare i32 @system(i8* noundef)
declare i32 @puts(i8* noundef)
declare i64 @strlen(i8* noundef)
declare i8* @malloc(i64 noundef)
declare void @free(i8* noundef)
declare i8* @strcpy(i8* noundef, i8* noundef)
declare i8* @strcat(i8* noundef, i8* noundef)
declare i32 @strcmp(i8* noundef, i8* noundef)
declare i8* @getenv(i8* noundef)
declare void @exit(i32 noundef) noreturn
declare i64 @atoi(i8* noundef)
declare double @atof(i8* noundef)
declare i32 @sprintf(i8* noundef, i8* noundef, ...)
declare i64 @write(i32 noundef, i8* noundef, i64 noundef)
declare i32 @usleep(i32 noundef)

"#,
            self.module_name
        );

        // Generate functions
        let mut fn_bodies = String::new();
        let fns: Vec<FunctionDecl> = self.functions.values().cloned().collect();

        // Always generate main wrapper if there's a main()
        for fn_decl in &fns {
            let body = self.gen_function(fn_decl)?;
            fn_bodies.push_str(&body);
            fn_bodies.push('\n');
        }

        // If no main function, generate empty main
        if !self.functions.contains_key("main") {
            fn_bodies.push_str("define i64 @main(i32 %argc, i8** %argv) {\nentry:\n  ret i64 0\n}\n\n");
        }

        // Build string constant pool
        let mut str_pool = String::new();
        let lits = self.str_lits.clone();
        for (idx, s) in lits.iter().enumerate() {
            let escaped = Self::escape_str(s);
            let len = s.len() + 1; // +1 for null terminator
            str_pool.push_str(&format!(
                "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\00\", align 1\n",
                idx, len, escaped
            ));
        }
        // printf format strings
        str_pool.push_str("@.fmt_int   = private unnamed_addr constant [4 x i8] c\"%ld\\00\", align 1\n");
        str_pool.push_str("@.fmt_float = private unnamed_addr constant [3 x i8] c\"%g\\00\", align 1\n");
        str_pool.push_str("@.fmt_str   = private unnamed_addr constant [3 x i8] c\"%s\\00\", align 1\n");
        str_pool.push_str("@.fmt_nl    = private unnamed_addr constant [2 x i8] c\"\\0A\\00\", align 1\n");
        str_pool.push_str("@.true_str  = private unnamed_addr constant [5 x i8] c\"true\\00\", align 1\n");
        str_pool.push_str("@.false_str = private unnamed_addr constant [6 x i8] c\"false\\00\", align 1\n");
        str_pool.push('\n');

        Ok(format!("{}\n{}\n{}", header, str_pool, fn_bodies))
    }

    fn escape_str(s: &str) -> String {
        let mut out = String::new();
        for c in s.chars() {
            match c {
                '\n' => out.push_str("\\0A"),
                '\t' => out.push_str("\\09"),
                '\r' => out.push_str("\\0D"),
                '"'  => out.push_str("\\22"),
                '\\' => out.push_str("\\5C"),
                c if c.is_ascii() && !c.is_control() => out.push(c),
                c    => out.push_str(&format!("\\{:02X}", c as u32)),
            }
        }
        out
    }

    // ── Function generation ───────────────────────────────────────────────────

    fn gen_function(&mut self, fn_decl: &FunctionDecl) -> Result<String, String> {
        self.locals.clear();
        self.tmp   = 0;
        self.label = 0;

        let ret_ll = fn_decl.ret_type.as_ref()
            .map(|t| ast_type_to_llvm(t))
            .unwrap_or(LLVMType::Void);

        let param_list: Vec<String> = fn_decl.params.iter()
            .map(|p| format!("{} %{}", ast_type_to_llvm(&p.ty).ir(), p.name))
            .collect();

        // entry is main
        let fn_name = if fn_decl.name == "main" {
            "main".to_string()
        } else {
            format!("rnf_{}", fn_decl.name)
        };

        let fn_sig = if fn_decl.name == "main" {
            format!("define i64 @{}(i32 %argc, i8** %argv)", fn_name)
        } else {
            format!("define {} @{}({})", ret_ll.ir(), fn_name, param_list.join(", "))
        };

        let mut body = format!("{} {{\nentry:\n", fn_sig);

        // Alloca for params
        for p in &fn_decl.params.clone() {
            let ll = ast_type_to_llvm(&p.ty);
            body.push_str(&format!("  %{}_ptr = alloca {}\n", p.name, ll.ir()));
            body.push_str(&format!("  store {} %{}, {}* %{}_ptr\n", ll.ir(), p.name, ll.ir(), p.name));
            self.locals.insert(p.name.clone(), (format!("%{}_ptr", p.name), ll));
        }

        let stmts = fn_decl.body.clone();
        let stmts_ir = self.gen_stmts(&stmts, &ret_ll)?;
        body.push_str(&stmts_ir);

        // Default return
        match ret_ll {
            LLVMType::Void => body.push_str("  ret void\n"),
            LLVMType::I64  => body.push_str("  ret i64 0\n"),
            LLVMType::I1   => body.push_str("  ret i1 0\n"),
            LLVMType::Double => body.push_str("  ret double 0.0\n"),
            _              => body.push_str("  ret i8* null\n"),
        }
        body.push_str("}\n");

        Ok(body)
    }

    // ── Statement IR generation ───────────────────────────────────────────────

    fn gen_stmts(&mut self, stmts: &[Stmt], ret_ty: &LLVMType) -> Result<String, String> {
        let mut out = String::new();
        for stmt in stmts {
            out.push_str(&self.gen_stmt(stmt, ret_ty)?);
        }
        Ok(out)
    }

    fn gen_stmt(&mut self, stmt: &Stmt, ret_ty: &LLVMType) -> Result<String, String> {
        let mut out = String::new();

        match stmt {
            Stmt::Let { name, ty, value } => {
                let (val_reg, val_ty, val_ir) = self.gen_expr(value)?;
                out.push_str(&val_ir);
                let ll_ty = ty.as_ref().map(ast_type_to_llvm).unwrap_or_else(|| val_ty.clone());
                out.push_str(&format!("  %{}_ptr = alloca {}\n", name, ll_ty.ir()));
                out.push_str(&format!("  store {} {}, {}* %{}_ptr\n",
                    ll_ty.ir(), val_reg, ll_ty.ir(), name));
                self.locals.insert(name.clone(), (format!("%{}_ptr", name), ll_ty));
            }

            Stmt::Assign { target, value } => {
                let (val_reg, val_ty, val_ir) = self.gen_expr(value)?;
                out.push_str(&val_ir);
                if let Expr::Ident(name) = target {
                    if let Some((ptr_reg, ty)) = self.locals.get(name).cloned() {
                        out.push_str(&format!("  store {} {}, {}* {}\n",
                            val_ty.ir(), val_reg, ty.ir(), ptr_reg));
                    } else {
                        // Define new variable
                        out.push_str(&format!("  %{}_ptr = alloca {}\n", name, val_ty.ir()));
                        out.push_str(&format!("  store {} {}, {}* %{}_ptr\n",
                            val_ty.ir(), val_reg, val_ty.ir(), name));
                        self.locals.insert(name.clone(), (format!("%{}_ptr", name), val_ty));
                    }
                }
            }

            Stmt::Return(expr) => {
                if let Some(e) = expr {
                    let (reg, ty, ir) = self.gen_expr(e)?;
                    out.push_str(&ir);
                    out.push_str(&format!("  ret {} {}\n", ty.ir(), reg));
                } else {
                    out.push_str("  ret void\n");
                }
                // Unreachable block for code after return
                let lbl = self.new_label();
                out.push_str(&format!("dead_{}:\n", lbl));
            }

            Stmt::Print(args) => {
                for arg in args {
                    let (reg, ty, ir) = self.gen_expr(arg)?;
                    out.push_str(&ir);
                    match ty {
                        LLVMType::I64 => {
                            let t = self.new_tmp();
                            out.push_str(&format!("  %t{} = getelementptr [4 x i8], [4 x i8]* @.fmt_int, i64 0, i64 0\n", t));
                            out.push_str(&format!("  call i32 (i8*, ...) @printf(i8* %t{}, i64 {})\n", t, reg));
                        }
                        LLVMType::Double => {
                            let t = self.new_tmp();
                            out.push_str(&format!("  %t{} = getelementptr [3 x i8], [3 x i8]* @.fmt_float, i64 0, i64 0\n", t));
                            out.push_str(&format!("  call i32 (i8*, ...) @printf(i8* %t{}, double {})\n", t, reg));
                        }
                        LLVMType::Ptr => {
                            let t = self.new_tmp();
                            out.push_str(&format!("  %t{} = getelementptr [3 x i8], [3 x i8]* @.fmt_str, i64 0, i64 0\n", t));
                            out.push_str(&format!("  call i32 (i8*, ...) @printf(i8* %t{}, i8* {})\n", t, reg));
                        }
                        LLVMType::I1 => {
                            // Print true/false
                            let t_lbl = self.new_label();
                            let f_lbl = self.new_label();
                            let end_lbl = self.new_label();
                            let t_str = self.new_tmp();
                            let f_str = self.new_tmp();
                            out.push_str(&format!("  br i1 {}, label %true_{}, label %false_{}\n", reg, t_lbl, f_lbl));
                            out.push_str(&format!("true_{}:\n", t_lbl));
                            out.push_str(&format!("  %t{} = getelementptr [5 x i8], [5 x i8]* @.true_str, i64 0, i64 0\n", t_str));
                            out.push_str(&format!("  call i32 @puts(i8* %t{})\n", t_str));
                            out.push_str(&format!("  br label %end_{}\n", end_lbl));
                            out.push_str(&format!("false_{}:\n", f_lbl));
                            out.push_str(&format!("  %f{} = getelementptr [6 x i8], [6 x i8]* @.false_str, i64 0, i64 0\n", f_str));
                            out.push_str(&format!("  call i32 @puts(i8* %f{})\n", f_str));
                            out.push_str(&format!("  br label %end_{}\n", end_lbl));
                            out.push_str(&format!("end_{}:\n", end_lbl));
                            continue;
                        }
                        _ => {}
                    }
                }
                // Print newline
                let t = self.new_tmp();
                out.push_str(&format!("  %nl{} = getelementptr [2 x i8], [2 x i8]* @.fmt_nl, i64 0, i64 0\n", t));
                out.push_str(&format!("  call i32 @puts(i8* %nl{})\n", t));
            }

            Stmt::Exec(cmd_expr) => {
                let (reg, _, ir) = self.gen_expr(cmd_expr)?;
                out.push_str(&ir);
                out.push_str(&format!("  call i32 @system(i8* {})\n", reg));
            }

            Stmt::If { cond, then_body, else_body } => {
                let (cond_reg, cond_ty, cond_ir) = self.gen_expr(cond)?;
                out.push_str(&cond_ir);

                // Convert to i1 if not already
                let bool_reg = if cond_ty != LLVMType::I1 {
                    let t = self.new_tmp();
                    out.push_str(&format!("  %t{} = icmp ne {} {}, 0\n", t, cond_ty.ir(), cond_reg));
                    format!("%t{}", t)
                } else { cond_reg };

                let then_lbl = self.new_label();
                let else_lbl = self.new_label();
                let end_lbl  = self.new_label();

                out.push_str(&format!("  br i1 {}, label %then_{}, label %else_{}\n", bool_reg, then_lbl, else_lbl));

                out.push_str(&format!("then_{}:\n", then_lbl));
                out.push_str(&self.gen_stmts(then_body, ret_ty)?);
                out.push_str(&format!("  br label %end_{}\n", end_lbl));

                out.push_str(&format!("else_{}:\n", else_lbl));
                if let Some(eb) = else_body {
                    out.push_str(&self.gen_stmts(eb, ret_ty)?);
                }
                out.push_str(&format!("  br label %end_{}\n", end_lbl));

                out.push_str(&format!("end_{}:\n", end_lbl));
            }

            Stmt::While { cond, body } => {
                let cond_lbl = self.new_label();
                let body_lbl = self.new_label();
                let end_lbl  = self.new_label();

                out.push_str(&format!("  br label %cond_{}\n", cond_lbl));
                out.push_str(&format!("cond_{}:\n", cond_lbl));

                let (cond_reg, cond_ty, cond_ir) = self.gen_expr(cond)?;
                out.push_str(&cond_ir);
                let bool_reg = if cond_ty != LLVMType::I1 {
                    let t = self.new_tmp();
                    out.push_str(&format!("  %t{} = icmp ne {} {}, 0\n", t, cond_ty.ir(), cond_reg));
                    format!("%t{}", t)
                } else { cond_reg };
                out.push_str(&format!("  br i1 {}, label %body_{}, label %end_{}\n", bool_reg, body_lbl, end_lbl));

                out.push_str(&format!("body_{}:\n", body_lbl));
                out.push_str(&self.gen_stmts(body, ret_ty)?);
                out.push_str(&format!("  br label %cond_{}\n", cond_lbl));

                out.push_str(&format!("end_{}:\n", end_lbl));
            }

            Stmt::Asm(raw) => {
                // Inline assembly via LLVM call asm directive
                out.push_str(&format!("  call void asm sideeffect \"{}\", \"\"\n", raw));
            }

            // Everything else: skip for now in codegen (use interpreter)
            _ => {
                out.push_str("  ; [unimplemented stmt skipped]\n");
            }
        }

        Ok(out)
    }

    // ── Expression IR generation ──────────────────────────────────────────────
    // Returns: (register_name, llvm_type, ir_instructions)

    fn gen_expr(&mut self, expr: &Expr) -> Result<(String, LLVMType, String), String> {
        match expr {
            Expr::Int(n) => Ok((n.to_string(), LLVMType::I64, String::new())),

            Expr::Float(f) => Ok((format!("{:e}", f), LLVMType::Double, String::new())),

            Expr::Bool(b) => Ok((if *b { "1" } else { "0" }.to_string(), LLVMType::I1, String::new())),

            Expr::Nil => Ok(("null".to_string(), LLVMType::Ptr, String::new())),

            Expr::Str(s) => {
                let idx = self.intern_str(s);
                let len = s.len() + 1;
                let t   = self.new_tmp();
                let ir  = format!(
                    "  %t{} = getelementptr [{} x i8], [{} x i8]* @.str.{}, i64 0, i64 0\n",
                    t, len, len, idx
                );
                Ok((format!("%t{}", t), LLVMType::Ptr, ir))
            }

            Expr::Ident(name) => {
                if let Some((ptr, ty)) = self.locals.get(name).cloned() {
                    let t = self.new_tmp();
                    let ir = format!("  %t{} = load {}, {}* {}\n", t, ty.ir(), ty.ir(), ptr);
                    Ok((format!("%t{}", t), ty, ir))
                } else {
                    Ok(("0".to_string(), LLVMType::I64, String::new()))
                }
            }

            Expr::Binary { op, left, right } => {
                let (lr, lt, li) = self.gen_expr(left)?;
                let (rr, _rt, ri) = self.gen_expr(right)?;
                let t = self.new_tmp();
                let mut ir = li + &ri;

                let (instr, out_ty) = match op {
                    BinOp::Add => match &lt {
                        LLVMType::I64    => (format!("  %t{} = add i64 {}, {}\n", t, lr, rr), LLVMType::I64),
                        LLVMType::Double => (format!("  %t{} = fadd double {}, {}\n", t, lr, rr), LLVMType::Double),
                        _                => (format!("  %t{} = add i64 0, 0\n", t), LLVMType::I64),
                    },
                    BinOp::Sub => match &lt {
                        LLVMType::I64    => (format!("  %t{} = sub i64 {}, {}\n", t, lr, rr), LLVMType::I64),
                        LLVMType::Double => (format!("  %t{} = fsub double {}, {}\n", t, lr, rr), LLVMType::Double),
                        _                => (format!("  %t{} = sub i64 0, 0\n", t), LLVMType::I64),
                    },
                    BinOp::Mul => match &lt {
                        LLVMType::I64    => (format!("  %t{} = mul i64 {}, {}\n", t, lr, rr), LLVMType::I64),
                        LLVMType::Double => (format!("  %t{} = fmul double {}, {}\n", t, lr, rr), LLVMType::Double),
                        _                => (format!("  %t{} = mul i64 0, 1\n", t), LLVMType::I64),
                    },
                    BinOp::Div => match &lt {
                        LLVMType::I64    => (format!("  %t{} = sdiv i64 {}, {}\n", t, lr, rr), LLVMType::I64),
                        LLVMType::Double => (format!("  %t{} = fdiv double {}, {}\n", t, lr, rr), LLVMType::Double),
                        _                => (format!("  %t{} = sdiv i64 1, 1\n", t), LLVMType::I64),
                    },
                    BinOp::Mod => (format!("  %t{} = srem i64 {}, {}\n", t, lr, rr), LLVMType::I64),
                    BinOp::Eq  => match &lt {
                        LLVMType::Double => (format!("  %t{} = fcmp oeq double {}, {}\n", t, lr, rr), LLVMType::I1),
                        _                => (format!("  %t{} = icmp eq {} {}, {}\n", t, lt.ir(), lr, rr), LLVMType::I1),
                    },
                    BinOp::Ne  => match &lt {
                        LLVMType::Double => (format!("  %t{} = fcmp one double {}, {}\n", t, lr, rr), LLVMType::I1),
                        _                => (format!("  %t{} = icmp ne {} {}, {}\n", t, lt.ir(), lr, rr), LLVMType::I1),
                    },
                    BinOp::Lt  => (format!("  %t{} = icmp slt i64 {}, {}\n", t, lr, rr), LLVMType::I1),
                    BinOp::Gt  => (format!("  %t{} = icmp sgt i64 {}, {}\n", t, lr, rr), LLVMType::I1),
                    BinOp::Le  => (format!("  %t{} = icmp sle i64 {}, {}\n", t, lr, rr), LLVMType::I1),
                    BinOp::Ge  => (format!("  %t{} = icmp sge i64 {}, {}\n", t, lr, rr), LLVMType::I1),
                    BinOp::And => (format!("  %t{} = and i1 {}, {}\n", t, lr, rr), LLVMType::I1),
                    BinOp::Or  => (format!("  %t{} = or i1 {}, {}\n", t, lr, rr), LLVMType::I1),
                };

                ir.push_str(&instr);
                Ok((format!("%t{}", t), out_ty, ir))
            }

            Expr::Unary { op, expr } => {
                let (reg, ty, ir) = self.gen_expr(expr)?;
                let t = self.new_tmp();
                let instr = match op {
                    UnOp::Neg => match &ty {
                        LLVMType::I64    => format!("  %t{} = sub i64 0, {}\n", t, reg),
                        LLVMType::Double => format!("  %t{} = fneg double {}\n", t, reg),
                        _                => format!("  %t{} = sub i64 0, {}\n", t, reg),
                    },
                    UnOp::Not => format!("  %t{} = xor i1 {}, 1\n", t, reg),
                };
                Ok((format!("%t{}", t), ty, ir + &instr))
            }

            Expr::Call { name, args } => {
                let mut ir = String::new();
                let mut arg_regs: Vec<(String, LLVMType)> = Vec::new();

                for arg in args {
                    let (r, ty, ai) = self.gen_expr(arg)?;
                    ir.push_str(&ai);
                    arg_regs.push((r, ty));
                }

                // Built-in print → puts/printf
                if name == "print" || name == "println" {
                    for (r, ty) in &arg_regs {
                        match ty {
                            LLVMType::Ptr => {
                                ir.push_str(&format!("  call i32 @puts(i8* {})\n", r));
                            }
                            LLVMType::I64 => {
                                let t = self.new_tmp();
                                ir.push_str(&format!("  %t{} = getelementptr [4 x i8], [4 x i8]* @.fmt_int, i64 0, i64 0\n", t));
                                ir.push_str(&format!("  call i32 (i8*, ...) @printf(i8* %t{}, i64 {})\n", t, r));
                                let t2 = self.new_tmp();
                                ir.push_str(&format!("  %nl{} = getelementptr [2 x i8], [2 x i8]* @.fmt_nl, i64 0, i64 0\n", t2));
                                ir.push_str(&format!("  call i32 @puts(i8* %nl{})\n", t2));
                            }
                            _ => {
                                let t = self.new_tmp();
                                ir.push_str(&format!("  %t{} = getelementptr [3 x i8], [3 x i8]* @.fmt_str, i64 0, i64 0\n", t));
                                ir.push_str(&format!("  call i32 (i8*, ...) @printf(i8* %t{}, i8* null)\n", t));
                            }
                        }
                    }
                    return Ok(("0".to_string(), LLVMType::I64, ir));
                }

                if name == "exec" {
                    if let Some((r, _)) = arg_regs.first() {
                        ir.push_str(&format!("  call i32 @system(i8* {})\n", r));
                    }
                    return Ok(("0".to_string(), LLVMType::I64, ir));
                }

                if name == "exit" {
                    if let Some((r, _)) = arg_regs.first() {
                        let t = self.new_tmp();
                        ir.push_str(&format!("  %t{} = trunc i64 {} to i32\n", t, r));
                        ir.push_str(&format!("  call void @exit(i32 %t{})\n", t));
                    }
                    return Ok(("0".to_string(), LLVMType::I64, ir));
                }

                // User function call
                let fn_name = if name == "main" { "main".to_string() } else { format!("rnf_{}", name) };
                let ret_ty = self.functions.get(name).and_then(|f| f.ret_type.as_ref())
                    .map(ast_type_to_llvm).unwrap_or(LLVMType::Void);

                let args_str: Vec<String> = arg_regs.iter()
                    .map(|(r, ty)| format!("{} {}", ty.ir(), r))
                    .collect();

                let t = self.new_tmp();
                if ret_ty == LLVMType::Void {
                    ir.push_str(&format!("  call void @{}({})\n", fn_name, args_str.join(", ")));
                    return Ok(("0".to_string(), LLVMType::I64, ir));
                }
                ir.push_str(&format!("  %t{} = call {} @{}({})\n", t, ret_ty.ir(), fn_name, args_str.join(", ")));
                Ok((format!("%t{}", t), ret_ty, ir))
            }

            Expr::Ref(inner) => {
                // In codegen, & on a variable gives its alloca pointer
                if let Expr::Ident(name) = inner.as_ref() {
                    if let Some((ptr, _ty)) = self.locals.get(name).cloned() {
                        return Ok((ptr, LLVMType::Ptr, String::new()));
                    }
                }
                Ok(("null".to_string(), LLVMType::Ptr, String::new()))
            }

            Expr::RawMem(addr_expr) => {
                let (reg, _, ir) = self.gen_expr(addr_expr)?;
                let t = self.new_tmp();
                let cast_ir = format!("  %t{} = inttoptr i64 {} to i8*\n", t, reg);
                Ok((format!("%t{}", t), LLVMType::Ptr, ir + &cast_ir))
            }

            _ => Ok(("0".to_string(), LLVMType::I64, String::new())),
        }
    }
}

// ── Build Pipeline ────────────────────────────────────────────────────────────

pub fn compile_to_binary(
    ir_path: &Path,
    obj_path: &Path,
    bin_path: &Path,
) {
    // Step 1: llc  →  IR to object
    println!("{} Compiling LLVM IR → object…", "→".cyan());
    let llc = std::process::Command::new("llc")
        .args([
            "-O2",
            "-relocation-model=pic",
            "-filetype=obj",
            ir_path.to_str().unwrap(),
            "-o",
            obj_path.to_str().unwrap(),
        ])
        .status();

    match llc {
        Ok(s) if s.success() => {
            println!("{} llc succeeded", "✓".green());
            link_binary(obj_path, bin_path);
        }
        Ok(_) | Err(_) => {
            eprintln!("{} llc failed — trying clang fallback…", "!".yellow());
            clang_fallback(ir_path, bin_path);
        }
    }
}

fn link_binary(obj_path: &Path, bin_path: &Path) {
    // Step 2: musl-gcc or gcc/cc  →  static link
    println!("{} Linking (static, musl)…", "→".cyan());

    // Try musl-gcc first, fallback to cc
    let linker = if std::process::Command::new("musl-gcc")
        .arg("--version").output().is_ok() { "musl-gcc" } else { "cc" };

    let mut flags = vec![
        "-static",
        "-s",           // strip
        "-O2",
        obj_path.to_str().unwrap(),
        "-o",
        bin_path.to_str().unwrap(),
    ];

    if linker == "cc" {
        flags.push("-static-libgcc");
    }

    let status = std::process::Command::new(linker)
        .args(&flags)
        .status();

    match status {
        Ok(s) if s.success() => println!("{} Linked with {}", "✓".green(), linker),
        _ => eprintln!("{} Linking failed. Check that {} and libc-static are installed.", "✗".red(), linker),
    }
}

fn clang_fallback(ir_path: &Path, bin_path: &Path) {
    println!("{} Trying clang fallback…", "→".cyan());
    let status = std::process::Command::new("clang")
        .args([
            "-O2",
            "-static",
            "-s",
            ir_path.to_str().unwrap(),
            "-o",
            bin_path.to_str().unwrap(),
            "-target",
            "x86_64-unknown-linux-musl",
        ])
        .status();

    match status {
        Ok(s) if s.success() => println!("{} clang succeeded", "✓".green()),
        _ => {
            eprintln!("{} clang fallback failed.", "✗".red());
            eprintln!("  Install: llvm, clang, musl-tools (apt/pacman/brew)");
            eprintln!("  Ubuntu:  sudo apt install llvm clang musl-tools");
            eprintln!("  Arch:    sudo pacman -S llvm clang musl");
            std::process::exit(1);
        }
    }
}
